services:
  crate:
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CRATE_PUBLIC_BASE_PATH: ${CRATE_PUBLIC_BASE_PATH:-./}
    environment:
      PORT: ${PORT:-3000}
      NODE_ENV: production
      CHATWOOT_BASE_URL: ${CHATWOOT_BASE_URL}
      CHATWOOT_APP_TOKEN: ${CHATWOOT_APP_TOKEN:-}
      CRATE_GOOGLE_DRIVE_SAVE_ALL_ENABLED: ${CRATE_GOOGLE_DRIVE_SAVE_ALL_ENABLED:-false}
      CRATE_GOOGLE_DRIVE_CLIENT_ID: ${CRATE_GOOGLE_DRIVE_CLIENT_ID:-}
      CRATE_GOOGLE_DRIVE_FOLDER_PREFIX: ${CRATE_GOOGLE_DRIVE_FOLDER_PREFIX:-Crate}
    ports:
      - "${HOST_PORT:-3000}:3000"
